# kubectl get configmap aws-auth -n kube-system -o yaml..
# use the above command to get the info of the below..
apiVersion: v1
data:
  mapRoles: |
     - rolearn: arn:aws:iam::981026210967:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-cBMpCwNx6L5j
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::981026210967:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-28T10:16:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1275"
  uid: c1768fba-84f1-4a27-b4cd-d82f4d138971

