# kubectl get configmap aws-auth -n kube-system -o yaml..
# use the above command to get the info of the below..
apiVersion: v1
data:
  mapRoles: |
      - rolearn: arn:aws:iam::981026210967:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-RDGPgLZTkKYh
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::981026210967:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-29T08:44:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1104"
  uid: 4cc84f5d-f93a-439d-869c-a4e00507b65c


